title: Kekei's First website
author: Raquel Baptista
email: raquelcbaptista53@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is only a test

# social links
twitter_username: raquelbaptista
github_username:  Raquel Baptista

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
